create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  salon_id bigint not null,
  user_id text,
  user_name text not null default '',
  action text not null,
  entity_type text not null,
  entity_id text,
  old_data jsonb,
  new_data jsonb,
  reason text not null,
  created_at timestamptz not null default now()
);

create index if not exists audit_logs_salon_created_at
  on public.audit_logs (salon_id, created_at desc);

create index if not exists audit_logs_salon_entity
  on public.audit_logs (salon_id, entity_type, entity_id);
