create table if not exists public.cash_closures (
  id bigint generated by default as identity primary key,
  salon_id bigint not null,
  date date not null,
  total_received numeric not null default 0,
  pix_total numeric not null default 0,
  cash_total numeric not null default 0,
  debit_total numeric not null default 0,
  credit_total numeric not null default 0,
  pending_total numeric not null default 0,
  outcome_total numeric not null default 0,
  commission_total numeric not null default 0,
  salon_profit numeric not null default 0,
  final_balance numeric not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists cash_closures_unique_day
  on public.cash_closures (salon_id, date);

create table if not exists public.employee_commission_payments (
  id bigint generated by default as identity primary key,
  salon_id bigint not null,
  employee_id bigint,
  employee_name text not null,
  amount numeric not null default 0,
  payment_method text not null,
  notes text,
  period_start date not null,
  period_end date not null,
  paid_at timestamptz not null default now(),
  cash_movement_ids bigint[] not null default '{}'
);

create index if not exists employee_commission_payments_salon_paid_at
  on public.employee_commission_payments (salon_id, paid_at desc);

do $$
begin
  if to_regclass('public.commission_payments') is not null then
    insert into public.employee_commission_payments (
      salon_id,
      employee_id,
      employee_name,
      amount,
      payment_method,
      notes,
      period_start,
      period_end,
      paid_at,
      cash_movement_ids
    )
    select
      legacy.salon_id,
      legacy.employee_id,
      legacy.employee_name,
      legacy.amount,
      legacy.payment_method,
      legacy.notes,
      legacy.period_start,
      legacy.period_end,
      legacy.paid_at,
      legacy.cash_movement_ids
    from public.commission_payments legacy
    where not exists (
      select 1
      from public.employee_commission_payments official
      where official.salon_id = legacy.salon_id
        and official.employee_id is not distinct from legacy.employee_id
        and official.paid_at = legacy.paid_at
    );
  end if;
end $$;
