create table if not exists public.cash_closures (
  id bigint generated by default as identity primary key,
  salon_id bigint not null,
  date date not null,
  total_received numeric not null default 0,
  pix_total numeric not null default 0,
  cash_total numeric not null default 0,
  debit_total numeric not null default 0,
  credit_total numeric not null default 0,
  pending_total numeric not null default 0,
  outcome_total numeric not null default 0,
  commission_total numeric not null default 0,
  salon_profit numeric not null default 0,
  final_balance numeric not null default 0,
  created_at timestamptz not null default now()
);

create unique index if not exists cash_closures_unique_day
  on public.cash_closures (salon_id, date);

create table if not exists public.commission_payments (
  id bigint generated by default as identity primary key,
  salon_id bigint not null,
  employee_id bigint,
  employee_name text not null,
  amount numeric not null default 0,
  payment_method text not null,
  notes text,
  period_start date not null,
  period_end date not null,
  paid_at timestamptz not null default now(),
  cash_movement_ids bigint[] not null default '{}'
);

create index if not exists commission_payments_salon_paid_at
  on public.commission_payments (salon_id, paid_at desc);
