-- Padronizacao segura: banco em ingles, sem apagar colunas antigas.
-- Execute depois das migrations existentes.

create table if not exists public.employee_commission_payments (
  id bigint generated by default as identity primary key,
  salon_id bigint not null,
  employee_id bigint,
  employee_name text not null default '',
  amount numeric not null default 0,
  commission_gross numeric not null default 0,
  advances_total numeric not null default 0,
  payment_method text not null default '',
  notes text,
  period_start date not null,
  period_end date not null,
  paid_at timestamptz not null default now(),
  cash_movement_ids bigint[] not null default '{}',
  advance_ids bigint[] not null default '{}'
);

alter table if exists public.employees
  add column if not exists salon_id bigint,
  add column if not exists name text,
  add column if not exists phone text,
  add column if not exists role text,
  add column if not exists functions text,
  add column if not exists email text,
  add column if not exists login_active boolean not null default false,
  add column if not exists active boolean not null default true,
  add column if not exists created_at timestamptz not null default now();

do $$
begin
  if to_regclass('public.employees') is not null then
    update public.employees
    set
      functions = coalesce(functions, role, ''),
      email = coalesce(email, ''),
      login_active = coalesce(login_active, false),
      active = coalesce(active, true)
    where true;
  end if;
end $$;

alter table if exists public.advances
  add column if not exists salon_id bigint,
  add column if not exists employee_id bigint,
  add column if not exists employee_name text,
  add column if not exists amount numeric not null default 0,
  add column if not exists value numeric not null default 0,
  add column if not exists status text not null default 'pendente',
  add column if not exists notes text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists discounted_at timestamptz,
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancelled_reason text;

alter table if exists public.cash_movements
  add column if not exists salon_id bigint,
  add column if not exists appointment_id bigint,
  add column if not exists employee_id bigint,
  add column if not exists service_id bigint,
  add column if not exists client_name text,
  add column if not exists service_name text,
  add column if not exists employee_name text,
  add column if not exists amount numeric not null default 0,
  add column if not exists service_value numeric not null default 0,
  add column if not exists commission_percent numeric not null default 0,
  add column if not exists commission_value numeric not null default 0,
  add column if not exists salon_value numeric not null default 0,
  add column if not exists payment_method text,
  add column if not exists payment_status text not null default 'pago',
  add column if not exists type text not null default 'entrada',
  add column if not exists category text,
  add column if not exists description text,
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancelled_reason text,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz;

do $$
begin
  if to_regclass('public.cash_movements') is not null then
    if exists (
      select 1
      from information_schema.columns
      where table_schema = 'public'
        and table_name = 'cash_movements'
        and column_name = 'value'
    ) then
      update public.cash_movements
      set
        amount = coalesce(nullif(amount, 0), nullif(service_value, 0), value, 0),
        description = coalesce(description, ''),
        category = coalesce(category, ''),
        payment_method = coalesce(payment_method, ''),
        updated_at = coalesce(updated_at, created_at)
      where true;
    else
      update public.cash_movements
      set
        amount = coalesce(nullif(amount, 0), nullif(service_value, 0), 0),
        description = coalesce(description, ''),
        category = coalesce(category, ''),
        payment_method = coalesce(payment_method, ''),
        updated_at = coalesce(updated_at, created_at)
      where true;
    end if;
  end if;
end $$;

do $$
begin
  if to_regclass('public.advances') is not null then
    update public.advances
    set amount = coalesce(nullif(amount, 0), value, 0)
    where true;
  end if;
end $$;

do $$
begin
  if to_regclass('public.commission_payments') is not null then
    insert into public.employee_commission_payments (
      salon_id,
      employee_id,
      employee_name,
      amount,
      commission_gross,
      advances_total,
      payment_method,
      notes,
      period_start,
      period_end,
      paid_at,
      cash_movement_ids,
      advance_ids
    )
    select
      legacy.salon_id,
      legacy.employee_id,
      legacy.employee_name,
      legacy.amount,
      legacy.amount,
      0,
      legacy.payment_method,
      legacy.notes,
      legacy.period_start,
      legacy.period_end,
      legacy.paid_at,
      coalesce(legacy.cash_movement_ids, '{}'),
      '{}'
    from public.commission_payments legacy
    where not exists (
      select 1
      from public.employee_commission_payments official
      where official.salon_id = legacy.salon_id
        and official.employee_id is not distinct from legacy.employee_id
        and official.paid_at = legacy.paid_at
    );
  end if;
end $$;

create index if not exists employees_salon_id_idx
  on public.employees (salon_id);

create index if not exists advances_salon_employee_status_created
  on public.advances (salon_id, employee_id, status, created_at desc);

create index if not exists cash_movements_salon_created_idx
  on public.cash_movements (salon_id, created_at desc);

create index if not exists employee_commission_payments_salon_paid_at
  on public.employee_commission_payments (salon_id, paid_at desc);
