-- SaaS multi-saloes: plano Premium unico, painel Master e trilhas de seguranca.
-- Execute no Supabase depois das migrations atuais.

alter table if exists public.salons
  add column if not exists whatsapp text not null default '',
  add column if not exists subscription_status text not null default 'ativo',
  add column if not exists subscription_due_date date,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

alter table if exists public.users
  add column if not exists name text,
  add column if not exists username text,
  add column if not exists role text not null default 'admin',
  add column if not exists salon_id uuid,
  add column if not exists login_active boolean not null default true,
  add column if not exists last_login_at timestamptz,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.subscriptions (
  id bigint generated by default as identity primary key,
  salon_id uuid not null references public.salons(id) on delete cascade,
  status text not null default 'ativo',
  amount numeric(10, 2) not null default 49.90,
  next_due_date date,
  provider text not null default 'manual',
  provider_subscription_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint subscriptions_salon_unique unique (salon_id),
  constraint subscriptions_status_check check (status in ('ativo', 'inativo', 'suspenso')),
  constraint subscriptions_amount_check check (amount = 49.90)
);

create table if not exists public.backup_logs (
  id bigint generated by default as identity primary key,
  salon_id uuid references public.salons(id) on delete cascade,
  status text not null default 'pendente',
  provider text not null default 'manual',
  file_url text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.login_attempts (
  id bigint generated by default as identity primary key,
  salon_id uuid references public.salons(id) on delete cascade,
  user_id uuid,
  email text,
  success boolean not null default false,
  ip_address text,
  user_agent text,
  reason text,
  created_at timestamptz not null default now()
);

create table if not exists public.session_logs (
  id bigint generated by default as identity primary key,
  salon_id uuid references public.salons(id) on delete cascade,
  user_id uuid,
  action text not null,
  ip_address text,
  user_agent text,
  created_at timestamptz not null default now()
);

alter table if exists public.audit_logs
  add column if not exists salon_id uuid,
  add column if not exists user_id uuid,
  add column if not exists user_name text,
  add column if not exists action text,
  add column if not exists entity_type text,
  add column if not exists entity_id text,
  add column if not exists old_data jsonb,
  add column if not exists new_data jsonb,
  add column if not exists reason text,
  add column if not exists created_at timestamptz not null default now();

do $$
begin
  if to_regclass('public.users') is not null then
    update public.users
    set role = case
      when lower(role) in ('platform_owner', 'admin', 'caixa', 'profissional') then lower(role)
      when lower(role) = 'cashier' then 'caixa'
      when lower(role) = 'professional' then 'profissional'
      else 'admin'
    end
    where role is not null;
  end if;
end $$;

alter table if exists public.users
  drop constraint if exists users_role_check;

alter table if exists public.users
  add constraint users_role_check check (role in ('platform_owner', 'admin', 'caixa', 'profissional'));

alter table if exists public.salons
  drop constraint if exists salons_subscription_status_check;

alter table if exists public.salons
  add constraint salons_subscription_status_check check (subscription_status in ('ativo', 'inativo', 'suspenso'));

insert into public.subscriptions (salon_id, status, amount, next_due_date)
select id, subscription_status, 49.90, subscription_due_date
from public.salons
on conflict (salon_id) do update
set
  status = excluded.status,
  amount = 49.90,
  next_due_date = excluded.next_due_date,
  updated_at = now();

-- Perfil do dono da plataforma. Crie o usuario no Supabase Auth com:
-- email: douglasnobrega@salaopro.com
-- login exibido: douglasnobrega
-- senha temporaria informada fora do frontend.
insert into public.users (id, email, username, name, role, salon_id, login_active)
select auth.users.id, 'douglasnobrega@salaopro.com', 'douglasnobrega', 'Douglas Nobrega', 'platform_owner', null, true
from auth.users
where auth.users.email = 'douglasnobrega@salaopro.com'
on conflict (id) do update
set
  username = excluded.username,
  name = excluded.name,
  role = 'platform_owner',
  salon_id = null,
  login_active = true,
  updated_at = now();

create index if not exists salons_subscription_status_idx
  on public.salons (subscription_status);

create index if not exists subscriptions_salon_status_idx
  on public.subscriptions (salon_id, status, next_due_date);

create index if not exists users_salon_role_idx
  on public.users (salon_id, role);

create index if not exists users_username_idx
  on public.users (username);

create index if not exists login_attempts_user_created_idx
  on public.login_attempts (user_id, created_at desc);

create index if not exists session_logs_user_created_idx
  on public.session_logs (user_id, created_at desc);

create index if not exists backup_logs_salon_created_idx
  on public.backup_logs (salon_id, created_at desc);

alter table public.subscriptions enable row level security;
alter table public.backup_logs enable row level security;
alter table public.login_attempts enable row level security;
alter table public.session_logs enable row level security;

drop policy if exists "platform owner manages subscriptions" on public.subscriptions;
create policy "platform owner manages subscriptions"
on public.subscriptions
for all
to authenticated
using (exists (
  select 1 from public.users
  where users.id = auth.uid()
    and users.role = 'platform_owner'
))
with check (exists (
  select 1 from public.users
  where users.id = auth.uid()
    and users.role = 'platform_owner'
));

drop policy if exists "salon admins read own subscription" on public.subscriptions;
create policy "salon admins read own subscription"
on public.subscriptions
for select
to authenticated
using (exists (
  select 1 from public.users
  where users.id = auth.uid()
    and users.salon_id = subscriptions.salon_id
));
