-- Correcao ponta a ponta do fluxo de recebimento, caixa, comissoes e auditoria.
-- Idempotente: pode ser executada mais de uma vez no Supabase SQL Editor.

create table if not exists public.cash_movements (
  id bigint generated by default as identity primary key,
  salon_id bigint not null,
  type text not null default 'entrada',
  description text,
  category text,
  payment_method text,
  amount numeric(10,2) not null default 0,
  date date not null default current_date,
  status text not null default 'pago',
  created_at timestamptz not null default now()
);

alter table public.cash_movements
  add column if not exists salon_id bigint,
  add column if not exists type text not null default 'entrada',
  add column if not exists description text,
  add column if not exists category text,
  add column if not exists payment_method text,
  add column if not exists date date not null default current_date,
  add column if not exists created_at timestamptz not null default now(),
  add column if not exists appointment_id bigint,
  add column if not exists employee_id bigint,
  add column if not exists service_id bigint,
  add column if not exists client_name text,
  add column if not exists service_name text,
  add column if not exists employee_name text,
  add column if not exists amount numeric(10,2) not null default 0,
  add column if not exists service_value numeric(10,2) not null default 0,
  add column if not exists discount numeric(10,2) not null default 0,
  add column if not exists desconto numeric(10,2) not null default 0,
  add column if not exists commission_percent numeric(10,2) not null default 0,
  add column if not exists commission_value numeric(10,2) not null default 0,
  add column if not exists salon_value numeric(10,2) not null default 0,
  add column if not exists payment_status text not null default 'pago',
  add column if not exists notes text,
  add column if not exists observacao text,
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancelled_reason text,
  add column if not exists updated_at timestamptz,
  add column if not exists commission_paid boolean not null default false,
  add column if not exists commission_paid_at timestamptz,
  add column if not exists commission_payment_method text,
  add column if not exists commission_notes text;

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'cash_movements' and column_name = 'value'
  ) then
    update public.cash_movements
    set amount = coalesce(nullif(amount, 0), nullif(service_value, 0), value, 0)
    where amount = 0;
  end if;

  update public.cash_movements
  set
    service_value = coalesce(nullif(service_value, 0), amount, 0),
    discount = coalesce(discount, desconto, 0),
    desconto = coalesce(desconto, discount, 0),
    payment_status = coalesce(payment_status, status, 'pago'),
    notes = coalesce(notes, observacao, ''),
    observacao = coalesce(observacao, notes, ''),
    updated_at = coalesce(updated_at, created_at)
  where true;
end $$;

create unique index if not exists cash_movements_unique_appointment
  on public.cash_movements (salon_id, appointment_id)
  where appointment_id is not null;

create index if not exists cash_movements_salon_date_idx
  on public.cash_movements (salon_id, date desc);

create table if not exists public.cash_closures (
  id bigint generated by default as identity primary key,
  salon_id bigint not null,
  date date not null,
  total_received numeric(10,2) not null default 0,
  pix_total numeric(10,2) not null default 0,
  cash_total numeric(10,2) not null default 0,
  debit_total numeric(10,2) not null default 0,
  credit_total numeric(10,2) not null default 0,
  pending_total numeric(10,2) not null default 0,
  outcome_total numeric(10,2) not null default 0,
  commission_total numeric(10,2) not null default 0,
  salon_profit numeric(10,2) not null default 0,
  final_balance numeric(10,2) not null default 0,
  notes text,
  observacao text,
  created_at timestamptz not null default now()
);

alter table public.cash_closures
  add column if not exists salon_id bigint,
  add column if not exists date date not null default current_date,
  add column if not exists total_received numeric(10,2) not null default 0,
  add column if not exists pix_total numeric(10,2) not null default 0,
  add column if not exists cash_total numeric(10,2) not null default 0,
  add column if not exists debit_total numeric(10,2) not null default 0,
  add column if not exists credit_total numeric(10,2) not null default 0,
  add column if not exists pending_total numeric(10,2) not null default 0,
  add column if not exists outcome_total numeric(10,2) not null default 0,
  add column if not exists commission_total numeric(10,2) not null default 0,
  add column if not exists salon_profit numeric(10,2) not null default 0,
  add column if not exists final_balance numeric(10,2) not null default 0,
  add column if not exists notes text,
  add column if not exists observacao text,
  add column if not exists created_at timestamptz not null default now();

create unique index if not exists cash_closures_unique_day
  on public.cash_closures (salon_id, date);

create index if not exists cash_closures_salon_date_idx
  on public.cash_closures (salon_id, date desc);

create table if not exists public.employee_commission_payments (
  id bigint generated by default as identity primary key,
  salon_id bigint not null,
  employee_id bigint,
  employee_name text not null default '',
  amount numeric(10,2) not null default 0,
  commission_gross numeric(10,2) not null default 0,
  advances_total numeric(10,2) not null default 0,
  payment_method text not null default '',
  notes text,
  period_start date not null default current_date,
  period_end date not null default current_date,
  paid_at timestamptz not null default now(),
  cash_movement_ids bigint[] not null default '{}',
  advance_ids bigint[] not null default '{}'
);

alter table public.employee_commission_payments
  add column if not exists salon_id bigint,
  add column if not exists employee_id bigint,
  add column if not exists employee_name text not null default '',
  add column if not exists amount numeric(10,2) not null default 0,
  add column if not exists commission_gross numeric(10,2) not null default 0,
  add column if not exists advances_total numeric(10,2) not null default 0,
  add column if not exists payment_method text not null default '',
  add column if not exists notes text,
  add column if not exists period_start date not null default current_date,
  add column if not exists period_end date not null default current_date,
  add column if not exists paid_at timestamptz not null default now(),
  add column if not exists cash_movement_ids bigint[] not null default '{}',
  add column if not exists advance_ids bigint[] not null default '{}';

create index if not exists employee_commission_payments_salon_paid_at
  on public.employee_commission_payments (salon_id, paid_at desc);

do $$
begin
  if to_regclass('public.commission_payments') is not null then
    insert into public.employee_commission_payments (
      salon_id, employee_id, employee_name, amount, commission_gross, advances_total,
      payment_method, notes, period_start, period_end, paid_at, cash_movement_ids, advance_ids
    )
    select
      legacy.salon_id,
      legacy.employee_id,
      legacy.employee_name,
      legacy.amount,
      coalesce(legacy.amount, 0),
      0,
      legacy.payment_method,
      legacy.notes,
      legacy.period_start,
      legacy.period_end,
      legacy.paid_at,
      coalesce(legacy.cash_movement_ids, '{}'),
      '{}'
    from public.commission_payments legacy
    where not exists (
      select 1
      from public.employee_commission_payments official
      where official.salon_id = legacy.salon_id
        and official.employee_id is not distinct from legacy.employee_id
        and official.paid_at = legacy.paid_at
    );
  end if;
end $$;

notify pgrst, 'reload schema';

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  salon_id bigint not null,
  user_id text,
  user_name text not null default '',
  action text not null,
  entity_type text not null,
  entity_id text,
  old_data jsonb,
  new_data jsonb,
  reason text not null default '',
  created_at timestamptz not null default now()
);

alter table public.audit_logs
  add column if not exists salon_id bigint,
  add column if not exists user_id text,
  add column if not exists user_name text not null default '',
  add column if not exists action text not null default '',
  add column if not exists entity_type text not null default '',
  add column if not exists entity_id text,
  add column if not exists old_data jsonb,
  add column if not exists new_data jsonb,
  add column if not exists reason text not null default '',
  add column if not exists created_at timestamptz not null default now();

create index if not exists audit_logs_salon_created_at
  on public.audit_logs (salon_id, created_at desc);

create index if not exists audit_logs_salon_entity
  on public.audit_logs (salon_id, entity_type, entity_id);

alter table public.appointments
  add column if not exists payment_status text not null default 'pendente',
  add column if not exists payment_method text;

alter table public.cash_movements enable row level security;
alter table public.cash_closures enable row level security;
alter table public.employee_commission_payments enable row level security;
alter table public.audit_logs enable row level security;

grant select, insert, update, delete on public.cash_movements to authenticated;
grant select, insert, update, delete on public.cash_closures to authenticated;
grant select, insert, update, delete on public.employee_commission_payments to authenticated;
grant select, insert, update, delete on public.audit_logs to authenticated;

do $$
begin
  if to_regclass('public.cash_movements_id_seq') is not null then
    grant usage, select on sequence public.cash_movements_id_seq to authenticated;
  end if;
  if to_regclass('public.cash_closures_id_seq') is not null then
    grant usage, select on sequence public.cash_closures_id_seq to authenticated;
  end if;
  if to_regclass('public.employee_commission_payments_id_seq') is not null then
    grant usage, select on sequence public.employee_commission_payments_id_seq to authenticated;
  end if;
  if to_regclass('public.audit_logs_id_seq') is not null then
    grant usage, select on sequence public.audit_logs_id_seq to authenticated;
  end if;
end $$;

do $$
begin
  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'cash_movements' and policyname = 'cash_movements_por_salao'
  ) then
    create policy cash_movements_por_salao on public.cash_movements
      for all
      using (salon_id in (select salon_id from public.users where id = auth.uid()))
      with check (salon_id in (select salon_id from public.users where id = auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'cash_closures' and policyname = 'cash_closures_por_salao'
  ) then
    create policy cash_closures_por_salao on public.cash_closures
      for all
      using (salon_id in (select salon_id from public.users where id = auth.uid()))
      with check (salon_id in (select salon_id from public.users where id = auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'employee_commission_payments' and policyname = 'employee_commission_payments_por_salao'
  ) then
    create policy employee_commission_payments_por_salao on public.employee_commission_payments
      for all
      using (salon_id in (select salon_id from public.users where id = auth.uid()))
      with check (salon_id in (select salon_id from public.users where id = auth.uid()));
  end if;

  if not exists (
    select 1 from pg_policies where schemaname = 'public' and tablename = 'audit_logs' and policyname = 'audit_logs_por_salao'
  ) then
    create policy audit_logs_por_salao on public.audit_logs
      for all
      using (salon_id in (select salon_id from public.users where id = auth.uid()))
      with check (salon_id in (select salon_id from public.users where id = auth.uid()));
  end if;
end $$;
